import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import ProgressBarProvider from "@/lib/ProgressBar";
import Navbar from "../components/utils/Navbar";
const inter = Inter({ subsets: ["latin"] });
import AuthProviders from "@/lib/AuthProvider";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AuthProviders>
      <ProgressBarProvider>
        <Navbar />
        {children}
        <Toaster />
       </ProgressBarProvider>
      </AuthProviders>
        </body>
    </html>
  );
}
